name: 'run-on-list'
description: 'Iterate over a list of things - list must be a json encoded string'
author: 'Stockopedia'
inputs:
  command:
    required: true
    description: command to run on each list item
  list: # change this
    required: true
    description: 'list of things to iterate over'
runs:
  using: 'node12'
  main: 'dist/index.js'
