name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths:
      - bla
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run all
      - uses: ./
        with:
          list: '["one", "two", "four"]'
          command: |
            echo $item 
